//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventureWorks
{
    using System;
    using System.Collections.Generic;
    
    public partial class Private_SysTypes
    {
        public string name { get; set; }
        public byte system_type_id { get; set; }
        public int user_type_id { get; set; }
        public int schema_id { get; set; }
        public Nullable<int> principal_id { get; set; }
        public short max_length { get; set; }
        public byte precision { get; set; }
        public byte scale { get; set; }
        public string collation_name { get; set; }
        public Nullable<bool> is_nullable { get; set; }
        public bool is_user_defined { get; set; }
        public bool is_assembly_type { get; set; }
        public int default_object_id { get; set; }
        public int rule_object_id { get; set; }
        public bool is_table_type { get; set; }
    }
}
